#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>

// ============================================================
// UART SIMULATION
// ============================================================

typedef struct {
    volatile uint32_t SR;   // Status register
    volatile uint32_t DR;   // Data register
    volatile uint32_t BRR;  // Baud rate register
    volatile uint32_t CR1;  // Control register 1
    volatile uint32_t CR2;  // Control register 2
    volatile uint32_t CR3;  // Control register 3
} USART_TypeDef;

USART_TypeDef* USART2 = (USART_TypeDef*)0x40004400;

// Simulated UART transmit
void uart_send_char(char c) {
    printf("%c", c);
    USART2->DR = c;
    USART2->SR |= 0x0080;  // TXE flag
}

void uart_send_string(const char* str) {
    while(*str) {
        uart_send_char(*str);
        str++;
    }
}

void uart_send_hex(uint32_t value) {
    char buffer[16];
    sprintf(buffer, "0x%08X", value);
    uart_send_string(buffer);
}

// ============================================================
// SPI SIMULATION
// ============================================================

typedef struct {
    volatile uint32_t CR1;   // Control register 1
    volatile uint32_t CR2;   // Control register 2
    volatile uint32_t SR;    // Status register
    volatile uint32_t DR;    // Data register
} SPI_TypeDef;

SPI_TypeDef* SPI1 = (SPI_TypeDef*)0x40013000;

uint8_t spi_transfer(uint8_t data_out) {
    SPI1->DR = data_out;
    // Wait for transfer complete (simulated)
    usleep(100);
    return SPI1->DR;
}

// ============================================================
// I2C SIMULATION
// ============================================================

typedef struct {
    volatile uint32_t CR1;   // Control register 1
    volatile uint32_t CR2;   // Control register 2
    volatile uint32_t SR1;   // Status register 1
    volatile uint32_t SR2;   // Status register 2
    volatile uint32_t DR;    // Data register
    volatile uint32_t CCR;   // Clock control register
} I2C_TypeDef;

I2C_TypeDef* I2C1 = (I2C_TypeDef*)0x40005400;

// ============================================================
// MAIN FUNCTION
// ============================================================

int main() {
    printf("\n========================================\n");
    printf("      COMMUNICATION PROTOCOLS DEMO      \n");
    printf("========================================\n\n");
    
    // ============================================================
    // 1. UART (Universal Asynchronous Receiver/Transmitter)
    // ============================================================
    
    printf("--- UART (Serial Communication) ---\n\n");
    
    printf("UART Configuration:\n");
    printf("  Baud Rate: 115200 bits/second\n");
    printf("  Data Bits: 8\n");
    printf("  Parity: None\n");
    printf("  Stop Bits: 1\n");
    printf("  Flow Control: None\n\n");
    
    printf("UART Frame Structure:\n");
    printf("  ┌─────┬────────┬──────┬─────┐\n");
    printf("  │START│ 8-Bits │PARITY│STOP │\n");
    printf("  │ Bit │  Data  │ (opt)│ Bit │\n");
    printf("  └─────┴────────┴──────┴─────┘\n\n");
    
    printf("UART Transmission:\n");
    uart_send_string("  Sending via UART: Hello from UART!\n");
    
    printf("\nUART Baud Rate Calculation:\n");
    uint32_t clock = 72000000;  // 72 MHz
    uint32_t baud = 115200;
    uint32_t usart_div = clock / baud;
    printf("  USARTDIV = Clock / Baud Rate = %d / %d = %d\n", 
           clock, baud, usart_div);
    printf("  BRR Register = %d\n\n", usart_div);
    
    // ============================================================
    // 2. SPI (Serial Peripheral Interface)
    // ============================================================
    
    printf("--- SPI (Serial Peripheral Interface) ---\n\n");
    
    printf("SPI Signals:\n");
    printf("  SCK  - Serial Clock (generated by master)\n");
    printf("  MOSI - Master Out, Slave In\n");
    printf("  MISO - Master In, Slave Out\n");
    printf("  CS   - Chip Select (active low)\n\n");
    
    printf("SPI Modes (CPOL/CPHA):\n");
    printf("  Mode 0: CPOL=0, CPHA=0 (idle low, sample rising edge)\n");
    printf("  Mode 1: CPOL=0, CPHA=1 (idle low, sample falling edge)\n");
    printf("  Mode 2: CPOL=1, CPHA=0 (idle high, sample falling edge)\n");
    printf("  Mode 3: CPOL=1, CPHA=1 (idle high, sample rising edge)\n\n");
    
    printf("SPI Transfer Example (Mode 0, 1 MHz):\n");
    printf("  Sending data to slave...\n");
    
    uint8_t tx_data[] = {0x55, 0xAA, 0x12, 0x34};
    printf("  TX: ");
    for(int i = 0; i < 4; i++) {
        printf("0x%02X ", tx_data[i]);
    }
    printf("\n");
    
    printf("  RX: ");
    for(int i = 0; i < 4; i++) {
        uint8_t rx = spi_transfer(tx_data[i]);
        printf("0x%02X ", rx);
    }
    printf(" (simulated response)\n\n");
    
    printf("SPI Daisy-Chain Configuration:\n");
    printf("  Master ──MOSI──▶ Slave1 ──MOSI──▶ Slave2\n");
    printf("  Master ◀──MISO── Slave1 ◀──MISO── Slave2\n");
    
    // ============================================================
    // 3. I2C (Inter-Integrated Circuit)
    // ============================================================
    
    printf("\n--- I2C (Inter-Integrated Circuit) ---\n\n");
    
    printf("I2C Signals:\n");
    printf("  SDA - Serial Data (bidirectional)\n");
    printf("  SCL - Serial Clock (master generated)\n");
    printf("  Both lines need pull-up resistors\n\n");
    
    printf("I2C Frame Structure:\n");
    printf("  ┌─────┬──────────┬───┬─────┬────────┬───┬─────┐\n");
    printf("  │START│ 7-bit    │R/W│ ACK │ 8-bit  │ACK│ STOP│\n");
    printf("  │     │ Address  │   │     │ Data   │   │     │\n");
    printf("  └─────┴──────────┴───┴─────┴────────┴───┴─────┘\n\n");
    
    printf("I2C Communication Example:\n");
    printf("  Reading from EEPROM at address 0x50:\n");
    printf("  1. START condition\n");
    printf("  2. Send 0x50 (address) + 0 (write bit)\n");
    printf("  3. Receive ACK\n");
    printf("  4. Send memory address 0x00\n");
    printf("  5. Receive ACK\n");
    printf("  6. RESTART condition\n");
    printf("  7. Send 0x50 (address) + 1 (read bit)\n");
    printf("  8. Receive ACK\n");
    printf("  9. Read data byte\n");
    printf("  10. Send NACK\n");
    printf("  11. STOP condition\n\n");
    
    printf("I2C Speed Modes:\n");
    printf("  Standard Mode: 100 kbps\n");
    printf("  Fast Mode: 400 kbps\n");
    printf("  Fast Mode Plus: 1 Mbps\n");
    printf("  High Speed Mode: 3.4 Mbps\n\n");
    
    printf("I2C Clock Calculation (100 kHz):\n");
    uint32_t i2c_clock = 36000000;  // 36 MHz
    uint32_t target = 100000;       // 100 kHz
    uint32_t ccr = i2c_clock / (2 * target);
    printf("  CCR = PCLK / (2 * Target) = %d / %d = %d\n", 
           i2c_clock, 2 * target, ccr);
    
    // ============================================================
    // 4. PROTOCOL COMPARISON
    // ============================================================
    
    printf("\n--- PROTOCOL COMPARISON ---\n\n");
    
    printf("┌────────────┬──────────┬──────────┬──────────┐\n");
    printf("│ Feature    │   UART   │   SPI    │   I2C    │\n");
    printf("├────────────┼──────────┼──────────┼──────────┤\n");
    printf("│ Wires      │ 3 (TX,RX)│ 4        │ 2 (SDA,SCL)│\n");
    printf("├────────────┼──────────┼──────────┼──────────┤\n");
    printf("│ Type       │Async     │Sync      │Sync      │\n");
    printf("├────────────┼──────────┼──────────┼──────────┤\n");
    printf("│ Duplex     │Full      │Full      │Half      │\n");
    printf("├────────────┼──────────┼──────────┼──────────┤\n");
    printf("│ Max Speed  │12 Mbps   │100 MHz   │5 Mbps    │\n");
    printf("├────────────┼──────────┼──────────┼──────────┤\n");
    printf("│ Multi-slave│No        │Yes (CS)  │Yes (addr)│\n");
    printf("├────────────┼──────────┼──────────┼──────────┤\n");
    printf("│ Complexity │Simple    │Medium    │Complex   │\n");
    printf("└────────────┴──────────┴──────────┴──────────┘\n");
    
    // ============================================================
    // 5. WHEN TO USE WHICH
    // ============================================================
    
    printf("\n--- WHEN TO USE ---\n\n");
    
    printf("UART is best for:\n");
    printf("  ✓ Debug logging to PC\n");
    printf("  ✓ GPS modules\n");
    printf("  ✓ Bluetooth modules\n");
    printf("  ✓ Simple point-to-point communication\n\n");
    
    printf("SPI is best for:\n");
    printf("  ✓ High-speed sensors (accelerometers)\n");
    printf("  ✓ Displays (OLED, TFT)\n");
    printf("  ✓ SD cards\n");
    printf("  ✓ ADC/DAC converters\n\n");
    
    printf("I2C is best for:\n");
    printf("  ✓ Multiple sensors on same bus\n");
    printf("  ✓ EEPROM memory\n");
    printf("  ✓ Temperature sensors\n");
    printf("  ✓ RTC (Real Time Clock)\n");
    
    // ============================================================
    // 6. TROUBLESHOOTING
    // ============================================================
    
    printf("\n--- TROUBLESHOOTING ---\n\n");
    
    printf("UART Issues:\n");
    printf("  • Wrong baud rate → garbled data\n");
    printf("  • Missing ground → random data\n");
    printf("  • TX/RX swapped → no data\n\n");
    
    printf("SPI Issues:\n");
    printf("  • Mode mismatch → corrupted data\n");
    printf("  • CS not asserted → slave ignores\n");
    printf("  • Clock too high → missed bits\n\n");
    
    printf("I2C Issues:\n");
    printf("  • Missing pull-ups → bus stuck\n");
    printf("  • Address wrong → no ACK\n");
    printf("  • Clock stretching not supported → failure\n");
    
    // ============================================================
    // 7. EXAMPLE: UART SENDING FORMATTED DATA
    // ============================================================
    
    printf("\n--- EXAMPLE: UART Logging ---\n\n");
    
    printf("Simulated sensor readings via UART:\n");
    
    for(int i = 0; i < 3; i++) {
        int temperature = 20 + i * 5;
        int humidity = 40 + i * 10;
        
        printf("  ");
        uart_send_string("Sensor: Temp=");
        char temp_str[8];
        sprintf(temp_str, "%d", temperature);
        uart_send_string(temp_str);
        uart_send_string("°C, Humidity=");
        char hum_str[8];
        sprintf(hum_str, "%d", humidity);
        uart_send_string(hum_str);
        uart_send_string("%\n");
        
        usleep(500000);
    }
    
    // ============================================================
    // SUMMARY
    // ============================================================
    
    printf("\n========================================\n");
    printf("           KEY TAKEAWAYS                \n");
    printf("========================================\n");
    printf("1. UART: Simple, full duplex, good for debug\n");
    printf("2. SPI: Fast, full duplex, needs CS pin per slave\n");
    printf("3. I2C: 2 wires, addressing, pull-ups required\n");
    printf("4. Baud rate must match exactly for UART\n");
    printf("5. SPI modes (CPOL/CPHA) must match between devices\n");
    printf("6. I2C needs proper pull-up resistor values\n");
    printf("========================================\n\n");
    
    return 0;
}
